name: cmeutils-dev
channels:
  - conda-forge
dependencies:
  - fresnel
  - freud
  - gsd=2.9
  - hoomd<4.0=*cpu*
  - mbuild
  - numpy
  - pip
  - python
  - matplotlib
  - pre-commit
  - pymbar >= 4.0
  - pytest
  - pytest-cov
  - rowan
